2025-03-10 13:56:00,948 INFO    Thread-351 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:00,958 INFO    Thread-351 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:00,967 INFO    Thread-351 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:00,972 INFO    Thread-351 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:00,975 INFO    Thread-351 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:00,979 INFO    Thread-351 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135600-wyak69fq/logs/debug.log
2025-03-10 13:56:00,982 INFO    Thread-351 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135600-wyak69fq/logs/debug-internal.log
2025-03-10 13:56:00,986 INFO    Thread-351 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:00,988 INFO    Thread-351 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:56:00,989 INFO    Thread-351 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:00,991 ERROR   Thread-351 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:01,005 INFO    Thread-351 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:11,093 INFO    Thread-352 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:11,099 INFO    Thread-352 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:11,105 INFO    Thread-352 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:11,109 INFO    Thread-352 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:11,114 INFO    Thread-352 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:11,118 INFO    Thread-352 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135611-vcpw83dk/logs/debug.log
2025-03-10 13:56:11,123 INFO    Thread-352 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135611-vcpw83dk/logs/debug-internal.log
2025-03-10 13:56:11,127 INFO    Thread-352 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:11,132 INFO    Thread-352 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:56:11,137 INFO    Thread-352 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:11,142 ERROR   Thread-352 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:11,154 INFO    Thread-352 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:12,416 INFO    Thread-353 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:12,428 INFO    Thread-353 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:12,440 INFO    Thread-353 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:12,444 INFO    Thread-353 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:12,446 INFO    Thread-353 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:12,448 INFO    Thread-353 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135612-3g0qziem/logs/debug.log
2025-03-10 13:56:12,449 INFO    Thread-353 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135612-3g0qziem/logs/debug-internal.log
2025-03-10 13:56:12,451 INFO    Thread-353 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:12,452 INFO    Thread-353 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:12,461 INFO    Thread-353 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:12,470 ERROR   Thread-353 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:12,486 INFO    Thread-353 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:22,550 INFO    Thread-354 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:22,562 INFO    Thread-354 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:22,570 INFO    Thread-354 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:22,577 INFO    Thread-354 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:22,586 INFO    Thread-354 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:22,594 INFO    Thread-354 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135622-i14yd92l/logs/debug.log
2025-03-10 13:56:22,602 INFO    Thread-354 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135622-i14yd92l/logs/debug-internal.log
2025-03-10 13:56:22,614 INFO    Thread-354 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:22,626 INFO    Thread-354 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:22,638 INFO    Thread-354 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:22,649 ERROR   Thread-354 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:22,667 INFO    Thread-354 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:23,497 INFO    Thread-355 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:23,502 INFO    Thread-355 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:23,507 INFO    Thread-355 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:23,512 INFO    Thread-355 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:23,517 INFO    Thread-355 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:23,522 INFO    Thread-355 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135623-y1m0n0af/logs/debug.log
2025-03-10 13:56:23,526 INFO    Thread-355 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135623-y1m0n0af/logs/debug-internal.log
2025-03-10 13:56:23,530 INFO    Thread-355 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:23,536 INFO    Thread-355 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:23,549 INFO    Thread-355 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:23,564 ERROR   Thread-355 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:23,606 INFO    Thread-355 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:33,670 INFO    Thread-356 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:33,679 INFO    Thread-356 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:33,689 INFO    Thread-356 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:33,697 INFO    Thread-356 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:33,702 INFO    Thread-356 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:33,708 INFO    Thread-356 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135633-rh1hmp3h/logs/debug.log
2025-03-10 13:56:33,721 INFO    Thread-356 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135633-rh1hmp3h/logs/debug-internal.log
2025-03-10 13:56:33,737 INFO    Thread-356 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:33,752 INFO    Thread-356 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:56:33,768 INFO    Thread-356 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:33,780 ERROR   Thread-356 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:33,800 INFO    Thread-356 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:34,593 INFO    Thread-357 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:34,598 INFO    Thread-357 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:34,603 INFO    Thread-357 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:34,608 INFO    Thread-357 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:34,613 INFO    Thread-357 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:34,618 INFO    Thread-357 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135634-w14ba00b/logs/debug.log
2025-03-10 13:56:34,622 INFO    Thread-357 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135634-w14ba00b/logs/debug-internal.log
2025-03-10 13:56:34,625 INFO    Thread-357 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:34,633 INFO    Thread-357 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'nesterov', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:56:34,639 INFO    Thread-357 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:34,645 ERROR   Thread-357 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:34,660 INFO    Thread-357 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:44,736 INFO    Thread-358 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:44,744 INFO    Thread-358 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:44,754 INFO    Thread-358 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:44,763 INFO    Thread-358 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:44,772 INFO    Thread-358 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:44,781 INFO    Thread-358 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135644-9xuaw937/logs/debug.log
2025-03-10 13:56:44,791 INFO    Thread-358 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135644-9xuaw937/logs/debug-internal.log
2025-03-10 13:56:44,804 INFO    Thread-358 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:44,812 INFO    Thread-358 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:44,822 INFO    Thread-358 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:44,833 ERROR   Thread-358 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:44,854 INFO    Thread-358 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:46,036 INFO    Thread-359 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:46,045 INFO    Thread-359 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:46,052 INFO    Thread-359 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:46,066 INFO    Thread-359 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:46,081 INFO    Thread-359 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:46,096 INFO    Thread-359 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135646-yvj2oxnx/logs/debug.log
2025-03-10 13:56:46,109 INFO    Thread-359 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135646-yvj2oxnx/logs/debug-internal.log
2025-03-10 13:56:46,117 INFO    Thread-359 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:46,121 INFO    Thread-359 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:46,128 INFO    Thread-359 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:46,135 ERROR   Thread-359 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:46,151 INFO    Thread-359 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:56,219 INFO    Thread-360 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:56,228 INFO    Thread-360 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:56,238 INFO    Thread-360 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:56,245 INFO    Thread-360 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:56,250 INFO    Thread-360 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:56,256 INFO    Thread-360 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135656-8ortxy6i/logs/debug.log
2025-03-10 13:56:56,262 INFO    Thread-360 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135656-8ortxy6i/logs/debug-internal.log
2025-03-10 13:56:56,267 INFO    Thread-360 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:56,272 INFO    Thread-360 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:56,280 INFO    Thread-360 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:56,290 ERROR   Thread-360 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:56,320 INFO    Thread-360 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:56:56,996 INFO    Thread-361 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:56:57,001 INFO    Thread-361 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:56:57,006 INFO    Thread-361 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:56:57,012 INFO    Thread-361 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:56:57,017 INFO    Thread-361 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:56:57,022 INFO    Thread-361 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135656-gghhz17e/logs/debug.log
2025-03-10 13:56:57,026 INFO    Thread-361 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135656-gghhz17e/logs/debug-internal.log
2025-03-10 13:56:57,031 INFO    Thread-361 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:56:57,035 INFO    Thread-361 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'sgd', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:56:57,039 INFO    Thread-361 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:56:57,042 ERROR   Thread-361 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:56:57,051 INFO    Thread-361 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:07,119 INFO    Thread-362 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:07,128 INFO    Thread-362 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:07,137 INFO    Thread-362 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:07,146 INFO    Thread-362 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:07,156 INFO    Thread-362 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:07,170 INFO    Thread-362 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135707-k0qfknou/logs/debug.log
2025-03-10 13:57:07,185 INFO    Thread-362 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135707-k0qfknou/logs/debug-internal.log
2025-03-10 13:57:07,202 INFO    Thread-362 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:07,218 INFO    Thread-362 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:57:07,230 INFO    Thread-362 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:07,240 ERROR   Thread-362 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:07,256 INFO    Thread-362 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:08,090 INFO    Thread-363 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:08,096 INFO    Thread-363 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:08,101 INFO    Thread-363 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:08,106 INFO    Thread-363 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:08,111 INFO    Thread-363 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:08,116 INFO    Thread-363 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135708-yf05xuv4/logs/debug.log
2025-03-10 13:57:08,121 INFO    Thread-363 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135708-yf05xuv4/logs/debug-internal.log
2025-03-10 13:57:08,128 INFO    Thread-363 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:08,142 INFO    Thread-363 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:57:08,158 INFO    Thread-363 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:08,173 ERROR   Thread-363 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:08,211 INFO    Thread-363 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:18,275 INFO    Thread-364 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:18,284 INFO    Thread-364 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:18,294 INFO    Thread-364 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:18,303 INFO    Thread-364 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:18,307 INFO    Thread-364 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:18,320 INFO    Thread-364 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135718-b522jpoe/logs/debug.log
2025-03-10 13:57:18,335 INFO    Thread-364 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135718-b522jpoe/logs/debug-internal.log
2025-03-10 13:57:18,350 INFO    Thread-364 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:18,366 INFO    Thread-364 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:57:18,381 INFO    Thread-364 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:18,392 ERROR   Thread-364 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:18,407 INFO    Thread-364 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:19,180 INFO    Thread-365 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:19,185 INFO    Thread-365 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:19,190 INFO    Thread-365 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:19,195 INFO    Thread-365 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:19,200 INFO    Thread-365 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:19,205 INFO    Thread-365 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135719-0yy2akh7/logs/debug.log
2025-03-10 13:57:19,210 INFO    Thread-365 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135719-0yy2akh7/logs/debug-internal.log
2025-03-10 13:57:19,214 INFO    Thread-365 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:19,218 INFO    Thread-365 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:57:19,229 INFO    Thread-365 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:19,244 ERROR   Thread-365 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:19,283 INFO    Thread-365 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:29,371 INFO    Thread-366 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:29,380 INFO    Thread-366 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:29,391 INFO    Thread-366 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:29,402 INFO    Thread-366 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:29,415 INFO    Thread-366 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:29,432 INFO    Thread-366 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135729-0bpbeker/logs/debug.log
2025-03-10 13:57:29,448 INFO    Thread-366 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135729-0bpbeker/logs/debug-internal.log
2025-03-10 13:57:29,464 INFO    Thread-366 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:29,478 INFO    Thread-366 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:57:29,489 INFO    Thread-366 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:29,496 ERROR   Thread-366 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:29,512 INFO    Thread-366 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:30,533 INFO    Thread-367 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:30,539 INFO    Thread-367 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:30,544 INFO    Thread-367 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:30,549 INFO    Thread-367 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:30,555 INFO    Thread-367 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:30,560 INFO    Thread-367 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135730-5xa3r3bf/logs/debug.log
2025-03-10 13:57:30,565 INFO    Thread-367 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135730-5xa3r3bf/logs/debug-internal.log
2025-03-10 13:57:30,572 INFO    Thread-367 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:30,580 INFO    Thread-367 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'nesterov', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:57:30,588 INFO    Thread-367 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:30,596 ERROR   Thread-367 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:30,633 INFO    Thread-367 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:40,727 INFO    Thread-368 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:40,739 INFO    Thread-368 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:40,750 INFO    Thread-368 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:40,761 INFO    Thread-368 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:40,770 INFO    Thread-368 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:40,779 INFO    Thread-368 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135740-6gwbzlv1/logs/debug.log
2025-03-10 13:57:40,795 INFO    Thread-368 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135740-6gwbzlv1/logs/debug-internal.log
2025-03-10 13:57:40,810 INFO    Thread-368 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:40,822 INFO    Thread-368 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'sgd', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:57:40,832 INFO    Thread-368 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:40,841 ERROR   Thread-368 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:40,857 INFO    Thread-368 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:41,482 INFO    Thread-369 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:41,493 INFO    Thread-369 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:41,504 INFO    Thread-369 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:41,516 INFO    Thread-369 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:41,528 INFO    Thread-369 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:41,543 INFO    Thread-369 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135741-9q2xj0lp/logs/debug.log
2025-03-10 13:57:41,559 INFO    Thread-369 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135741-9q2xj0lp/logs/debug-internal.log
2025-03-10 13:57:41,575 INFO    Thread-369 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:41,589 INFO    Thread-369 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:57:41,601 INFO    Thread-369 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:41,610 ERROR   Thread-369 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:41,625 INFO    Thread-369 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:51,685 INFO    Thread-370 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:51,694 INFO    Thread-370 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:51,707 INFO    Thread-370 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:51,716 INFO    Thread-370 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:51,728 INFO    Thread-370 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:51,744 INFO    Thread-370 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135751-snynlm3p/logs/debug.log
2025-03-10 13:57:51,760 INFO    Thread-370 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135751-snynlm3p/logs/debug-internal.log
2025-03-10 13:57:51,777 INFO    Thread-370 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:51,793 INFO    Thread-370 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:57:51,809 INFO    Thread-370 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:51,822 ERROR   Thread-370 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:51,842 INFO    Thread-370 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:57:52,488 INFO    Thread-371 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:57:52,497 INFO    Thread-371 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:57:52,507 INFO    Thread-371 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:57:52,516 INFO    Thread-371 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:57:52,521 INFO    Thread-371 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:57:52,528 INFO    Thread-371 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135752-pwr762je/logs/debug.log
2025-03-10 13:57:52,542 INFO    Thread-371 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135752-pwr762je/logs/debug-internal.log
2025-03-10 13:57:52,559 INFO    Thread-371 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:57:52,575 INFO    Thread-371 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'rmsprop', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:57:52,591 INFO    Thread-371 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:57:52,606 ERROR   Thread-371 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:57:52,628 INFO    Thread-371 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:02,704 INFO    Thread-372 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:02,719 INFO    Thread-372 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:02,734 INFO    Thread-372 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:02,749 INFO    Thread-372 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:02,764 INFO    Thread-372 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:02,781 INFO    Thread-372 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135802-z6sm291z/logs/debug.log
2025-03-10 13:58:02,798 INFO    Thread-372 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135802-z6sm291z/logs/debug-internal.log
2025-03-10 13:58:02,813 INFO    Thread-372 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:02,824 INFO    Thread-372 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:02,834 INFO    Thread-372 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:02,841 ERROR   Thread-372 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:02,856 INFO    Thread-372 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:12,927 INFO    Thread-373 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:12,938 INFO    Thread-373 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:12,947 INFO    Thread-373 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:12,953 INFO    Thread-373 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:12,958 INFO    Thread-373 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:12,964 INFO    Thread-373 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135812-uwo3a3py/logs/debug.log
2025-03-10 13:58:12,978 INFO    Thread-373 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135812-uwo3a3py/logs/debug-internal.log
2025-03-10 13:58:12,995 INFO    Thread-373 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:13,011 INFO    Thread-373 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:13,029 INFO    Thread-373 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:13,045 ERROR   Thread-373 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:13,067 INFO    Thread-373 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:14,603 INFO    Thread-374 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:14,611 INFO    Thread-374 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:14,618 INFO    Thread-374 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:14,626 INFO    Thread-374 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:14,635 INFO    Thread-374 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:14,647 INFO    Thread-374 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135814-lz6dxhey/logs/debug.log
2025-03-10 13:58:14,655 INFO    Thread-374 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135814-lz6dxhey/logs/debug-internal.log
2025-03-10 13:58:14,663 INFO    Thread-374 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:14,670 INFO    Thread-374 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:58:14,677 INFO    Thread-374 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:14,689 ERROR   Thread-374 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:14,711 INFO    Thread-374 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:24,781 INFO    Thread-375 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:24,786 INFO    Thread-375 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:24,791 INFO    Thread-375 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:24,795 INFO    Thread-375 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:24,800 INFO    Thread-375 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:24,806 INFO    Thread-375 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135824-oa309e3x/logs/debug.log
2025-03-10 13:58:24,812 INFO    Thread-375 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135824-oa309e3x/logs/debug-internal.log
2025-03-10 13:58:24,817 INFO    Thread-375 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:24,823 INFO    Thread-375 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:58:24,828 INFO    Thread-375 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:24,835 ERROR   Thread-375 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:24,873 INFO    Thread-375 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:25,952 INFO    Thread-376 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:25,963 INFO    Thread-376 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:25,970 INFO    Thread-376 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:25,976 INFO    Thread-376 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:25,981 INFO    Thread-376 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:25,986 INFO    Thread-376 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135825-nt65x03j/logs/debug.log
2025-03-10 13:58:25,992 INFO    Thread-376 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135825-nt65x03j/logs/debug-internal.log
2025-03-10 13:58:26,000 INFO    Thread-376 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:26,013 INFO    Thread-376 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:26,039 INFO    Thread-376 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:26,055 ERROR   Thread-376 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:26,090 INFO    Thread-376 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:36,142 INFO    Thread-377 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:36,151 INFO    Thread-377 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:36,162 INFO    Thread-377 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:36,172 INFO    Thread-377 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:36,184 INFO    Thread-377 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:36,200 INFO    Thread-377 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135836-1n4e4tou/logs/debug.log
2025-03-10 13:58:36,217 INFO    Thread-377 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135836-1n4e4tou/logs/debug-internal.log
2025-03-10 13:58:36,234 INFO    Thread-377 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:36,248 INFO    Thread-377 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:36,260 INFO    Thread-377 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:36,268 ERROR   Thread-377 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:36,284 INFO    Thread-377 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:36,932 INFO    Thread-378 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:36,937 INFO    Thread-378 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:36,942 INFO    Thread-378 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:36,947 INFO    Thread-378 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:36,952 INFO    Thread-378 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:36,958 INFO    Thread-378 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135836-l88yc86d/logs/debug.log
2025-03-10 13:58:36,962 INFO    Thread-378 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135836-l88yc86d/logs/debug-internal.log
2025-03-10 13:58:36,967 INFO    Thread-378 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:36,980 INFO    Thread-378 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:58:36,994 INFO    Thread-378 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:37,009 ERROR   Thread-378 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:37,048 INFO    Thread-378 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:47,131 INFO    Thread-379 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:47,142 INFO    Thread-379 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:47,152 INFO    Thread-379 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:47,162 INFO    Thread-379 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:47,167 INFO    Thread-379 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:47,181 INFO    Thread-379 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135847-jtjs2lq5/logs/debug.log
2025-03-10 13:58:47,198 INFO    Thread-379 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135847-jtjs2lq5/logs/debug-internal.log
2025-03-10 13:58:47,215 INFO    Thread-379 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:47,233 INFO    Thread-379 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:58:47,251 INFO    Thread-379 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:47,263 ERROR   Thread-379 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:47,282 INFO    Thread-379 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:48,165 INFO    Thread-380 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:48,174 INFO    Thread-380 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:48,183 INFO    Thread-380 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:48,192 INFO    Thread-380 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:48,200 INFO    Thread-380 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:48,214 INFO    Thread-380 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135848-ok5zfmfk/logs/debug.log
2025-03-10 13:58:48,231 INFO    Thread-380 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135848-ok5zfmfk/logs/debug-internal.log
2025-03-10 13:58:48,249 INFO    Thread-380 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:48,265 INFO    Thread-380 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:48,278 INFO    Thread-380 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:48,288 ERROR   Thread-380 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:48,301 INFO    Thread-380 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:58,365 INFO    Thread-381 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:58,370 INFO    Thread-381 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:58,376 INFO    Thread-381 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:58,383 INFO    Thread-381 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:58,390 INFO    Thread-381 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:58,398 INFO    Thread-381 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135858-pi5nuczs/logs/debug.log
2025-03-10 13:58:58,414 INFO    Thread-381 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135858-pi5nuczs/logs/debug-internal.log
2025-03-10 13:58:58,431 INFO    Thread-381 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:58,448 INFO    Thread-381 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:58,465 INFO    Thread-381 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:58,480 ERROR   Thread-381 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:58,502 INFO    Thread-381 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:58:59,174 INFO    Thread-382 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:58:59,184 INFO    Thread-382 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:58:59,194 INFO    Thread-382 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:58:59,204 INFO    Thread-382 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:58:59,208 INFO    Thread-382 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:58:59,213 INFO    Thread-382 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135859-q3giitb6/logs/debug.log
2025-03-10 13:58:59,217 INFO    Thread-382 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135859-q3giitb6/logs/debug-internal.log
2025-03-10 13:58:59,221 INFO    Thread-382 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:58:59,225 INFO    Thread-382 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 4, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:58:59,233 INFO    Thread-382 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:58:59,249 ERROR   Thread-382 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:58:59,294 INFO    Thread-382 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:09,368 INFO    Thread-383 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:09,374 INFO    Thread-383 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:09,380 INFO    Thread-383 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:09,386 INFO    Thread-383 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:09,392 INFO    Thread-383 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:09,398 INFO    Thread-383 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135909-40vfs3o7/logs/debug.log
2025-03-10 13:59:09,403 INFO    Thread-383 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135909-40vfs3o7/logs/debug-internal.log
2025-03-10 13:59:09,412 INFO    Thread-383 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:09,424 INFO    Thread-383 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:59:09,434 INFO    Thread-383 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:09,444 ERROR   Thread-383 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:09,472 INFO    Thread-383 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:10,292 INFO    Thread-384 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:10,305 INFO    Thread-384 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:10,315 INFO    Thread-384 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:10,320 INFO    Thread-384 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:10,325 INFO    Thread-384 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:10,330 INFO    Thread-384 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135910-8bnuoohr/logs/debug.log
2025-03-10 13:59:10,335 INFO    Thread-384 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135910-8bnuoohr/logs/debug-internal.log
2025-03-10 13:59:10,341 INFO    Thread-384 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:10,347 INFO    Thread-384 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:59:10,362 INFO    Thread-384 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:10,379 ERROR   Thread-384 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:10,420 INFO    Thread-384 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:20,486 INFO    Thread-385 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:20,497 INFO    Thread-385 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:20,508 INFO    Thread-385 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:20,517 INFO    Thread-385 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:20,527 INFO    Thread-385 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:20,540 INFO    Thread-385 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135920-0uqkvh85/logs/debug.log
2025-03-10 13:59:20,556 INFO    Thread-385 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135920-0uqkvh85/logs/debug-internal.log
2025-03-10 13:59:20,573 INFO    Thread-385 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:20,590 INFO    Thread-385 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:59:20,603 INFO    Thread-385 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:20,613 ERROR   Thread-385 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:20,631 INFO    Thread-385 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:21,331 INFO    Thread-386 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:21,336 INFO    Thread-386 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:21,341 INFO    Thread-386 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:21,346 INFO    Thread-386 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:21,352 INFO    Thread-386 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:21,358 INFO    Thread-386 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135921-m6h4athp/logs/debug.log
2025-03-10 13:59:21,364 INFO    Thread-386 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135921-m6h4athp/logs/debug-internal.log
2025-03-10 13:59:21,369 INFO    Thread-386 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:21,374 INFO    Thread-386 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'rmsprop', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:59:21,379 INFO    Thread-386 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:21,383 ERROR   Thread-386 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:21,395 INFO    Thread-386 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:31,491 INFO    Thread-387 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:31,499 INFO    Thread-387 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:31,507 INFO    Thread-387 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:31,514 INFO    Thread-387 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:31,522 INFO    Thread-387 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:31,530 INFO    Thread-387 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135931-m8sysjjk/logs/debug.log
2025-03-10 13:59:31,538 INFO    Thread-387 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135931-m8sysjjk/logs/debug-internal.log
2025-03-10 13:59:31,546 INFO    Thread-387 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:31,554 INFO    Thread-387 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:59:31,562 INFO    Thread-387 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:31,571 ERROR   Thread-387 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:31,593 INFO    Thread-387 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:32,737 INFO    Thread-388 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:32,743 INFO    Thread-388 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:32,749 INFO    Thread-388 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:32,753 INFO    Thread-388 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:32,757 INFO    Thread-388 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:32,760 INFO    Thread-388 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135932-akr1bz8x/logs/debug.log
2025-03-10 13:59:32,763 INFO    Thread-388 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135932-akr1bz8x/logs/debug-internal.log
2025-03-10 13:59:32,766 INFO    Thread-388 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:32,771 INFO    Thread-388 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:59:32,786 INFO    Thread-388 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:32,800 ERROR   Thread-388 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:32,826 INFO    Thread-388 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:42,897 INFO    Thread-389 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:42,907 INFO    Thread-389 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:42,918 INFO    Thread-389 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:42,924 INFO    Thread-389 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:42,935 INFO    Thread-389 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:42,948 INFO    Thread-389 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135942-g3xck8rp/logs/debug.log
2025-03-10 13:59:42,964 INFO    Thread-389 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135942-g3xck8rp/logs/debug-internal.log
2025-03-10 13:59:42,982 INFO    Thread-389 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:43,000 INFO    Thread-389 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:59:43,010 INFO    Thread-389 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:43,018 ERROR   Thread-389 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:43,033 INFO    Thread-389 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:43,720 INFO    Thread-390 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:43,731 INFO    Thread-390 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:43,742 INFO    Thread-390 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:43,752 INFO    Thread-390 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:43,761 INFO    Thread-390 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:43,774 INFO    Thread-390 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135943-gejralop/logs/debug.log
2025-03-10 13:59:43,789 INFO    Thread-390 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135943-gejralop/logs/debug-internal.log
2025-03-10 13:59:43,807 INFO    Thread-390 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:43,822 INFO    Thread-390 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 4, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 13:59:43,834 INFO    Thread-390 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:43,844 ERROR   Thread-390 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:43,856 INFO    Thread-390 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:53,903 INFO    Thread-391 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:53,908 INFO    Thread-391 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:53,914 INFO    Thread-391 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:53,920 INFO    Thread-391 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:53,925 INFO    Thread-391 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:53,930 INFO    Thread-391 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135953-g544pk18/logs/debug.log
2025-03-10 13:59:53,935 INFO    Thread-391 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135953-g544pk18/logs/debug-internal.log
2025-03-10 13:59:53,940 INFO    Thread-391 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:53,945 INFO    Thread-391 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:59:53,949 INFO    Thread-391 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:53,954 ERROR   Thread-391 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:53,976 INFO    Thread-391 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 13:59:54,765 INFO    Thread-392 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 13:59:54,774 INFO    Thread-392 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 13:59:54,784 INFO    Thread-392 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 13:59:54,790 INFO    Thread-392 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 13:59:54,794 INFO    Thread-392 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 13:59:54,799 INFO    Thread-392 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135954-e24qi5c2/logs/debug.log
2025-03-10 13:59:54,805 INFO    Thread-392 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_135954-e24qi5c2/logs/debug-internal.log
2025-03-10 13:59:54,813 INFO    Thread-392 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 13:59:54,829 INFO    Thread-392 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 13:59:54,846 INFO    Thread-392 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 13:59:54,864 ERROR   Thread-392 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 13:59:54,898 INFO    Thread-392 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 14:00:04,959 INFO    Thread-393 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 14:00:04,965 INFO    Thread-393 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 14:00:04,971 INFO    Thread-393 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 14:00:04,976 INFO    Thread-393 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 14:00:04,982 INFO    Thread-393 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 14:00:04,987 INFO    Thread-393 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140004-3ka0r9e0/logs/debug.log
2025-03-10 14:00:04,992 INFO    Thread-393 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140004-3ka0r9e0/logs/debug-internal.log
2025-03-10 14:00:04,997 INFO    Thread-393 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 14:00:05,002 INFO    Thread-393 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 16, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.0001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 14:00:05,006 INFO    Thread-393 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 14:00:05,011 ERROR   Thread-393 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 14:00:05,038 INFO    Thread-393 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 14:00:05,853 INFO    Thread-394 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 14:00:05,861 INFO    Thread-394 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 14:00:05,872 INFO    Thread-394 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 14:00:05,881 INFO    Thread-394 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 14:00:05,890 INFO    Thread-394 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 14:00:05,896 INFO    Thread-394 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140005-dsg7iius/logs/debug.log
2025-03-10 14:00:05,905 INFO    Thread-394 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140005-dsg7iius/logs/debug-internal.log
2025-03-10 14:00:05,921 INFO    Thread-394 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 14:00:05,931 INFO    Thread-394 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'sigmoid', 'batch_size': 64, 'epochs': 5, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'adam', 'weight_decay': 0.5, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 14:00:05,942 INFO    Thread-394 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 14:00:05,954 ERROR   Thread-394 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 14:00:05,984 INFO    Thread-394 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 14:08:43,140 INFO    Thread-395 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 14:08:43,149 INFO    Thread-395 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 14:08:43,158 INFO    Thread-395 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 14:08:43,167 INFO    Thread-395 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 14:08:43,176 INFO    Thread-395 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 14:08:43,183 INFO    Thread-395 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140843-0p3m2ych/logs/debug.log
2025-03-10 14:08:43,191 INFO    Thread-395 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140843-0p3m2ych/logs/debug-internal.log
2025-03-10 14:08:43,200 INFO    Thread-395 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 14:08:43,210 INFO    Thread-395 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layer_size': 128, 'learning_rate': 0.001, 'num_hidden_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 14:08:43,218 INFO    Thread-395 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 14:08:43,225 ERROR   Thread-395 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 14:08:43,240 INFO    Thread-395 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 14:08:53,359 INFO    Thread-396 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 14:08:53,366 INFO    Thread-396 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 14:08:53,373 INFO    Thread-396 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 14:08:53,378 INFO    Thread-396 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 14:08:53,383 INFO    Thread-396 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 14:08:53,389 INFO    Thread-396 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140853-0dwgczph/logs/debug.log
2025-03-10 14:08:53,397 INFO    Thread-396 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140853-0dwgczph/logs/debug-internal.log
2025-03-10 14:08:53,405 INFO    Thread-396 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 14:08:53,418 INFO    Thread-396 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 32, 'epochs': 5, 'hidden_layer_size': 64, 'learning_rate': 0.0001, 'num_hidden_layers': 5, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 14:08:53,433 INFO    Thread-396 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 14:08:53,447 ERROR   Thread-396 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 14:08:53,470 INFO    Thread-396 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 14:08:54,198 INFO    Thread-397 (_run_job):198064 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 14:08:54,205 INFO    Thread-397 (_run_job):198064 [wandb_setup.py:_flush():67] Configure stats pid to 198064
2025-03-10 14:08:54,213 INFO    Thread-397 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/.config/wandb/settings
2025-03-10 14:08:54,220 INFO    Thread-397 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from /home/snehal/Downloads/dl_ass1/wandb/settings
2025-03-10 14:08:54,228 INFO    Thread-397 (_run_job):198064 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 14:08:54,237 INFO    Thread-397 (_run_job):198064 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140854-lh73b5bm/logs/debug.log
2025-03-10 14:08:54,246 INFO    Thread-397 (_run_job):198064 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/snehal/Downloads/dl_ass1/wandb/run-20250310_140854-lh73b5bm/logs/debug-internal.log
2025-03-10 14:08:54,263 INFO    Thread-397 (_run_job):198064 [wandb_init.py:init():761] calling init triggers
2025-03-10 14:08:54,279 INFO    Thread-397 (_run_job):198064 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation_function': 'tanh', 'batch_size': 64, 'epochs': 10, 'hidden_layer_size': 32, 'learning_rate': 0.001, 'num_hidden_layers': 3, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 14:08:54,294 INFO    Thread-397 (_run_job):198064 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 14:08:54,307 ERROR   Thread-397 (_run_job):198064 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/snehal/Downloads/dl_ass1/dvenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-10 14:08:54,330 INFO    Thread-397 (_run_job):198064 [wandb_run.py:_finish():2112] finishing run snehalma23m020-iit-madras/DLassignment1/hx7kfgf3
2025-03-10 14:08:54,391 INFO    MainThread:198064 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 14:08:54,395 INFO    MainThread:198064 [wandb_init.py:_pause_backend():564] pausing backend
